name: Leonardo Miceli
markdown: kramdown

source: ./_bibliography
bibliography: leo.bib

details_dir:    bibliography
details_layout: bibtex.html
details_link: more

permalink: /blog/:year/:month/:day/:title
